blog/urls.py
from django.urls import path
from . import views

"""
URL config for 'blog' app

"""

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='homepage'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE, 
        related_name='blog_posts'
    )
    content = models.TextField()
    status =models.CharField(max_length=10, choices=options, default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return f"{self.title}"

blog/views.py
from django.shortcuts import render

from .models import Post

# Create your views here.

def home(request):

    all_posts = Post.objects.all()

    return render(request, 'blog/index.html', {"posts": all_posts})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
        crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">My Blog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href={% url 'blog:homepage' %}>Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>

          </div>
        </div>
      </nav>

    {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" 
    crossorigin="anonymous">
    </script>

</body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}My Blog{% endblock title %}

{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            
            {% for post in posts %}

                {{ post}}
                {{ post.author|linebreaks  }}

            {% endfor %}
            

        </div>
    </div>
</div>
{% endblock content %}

    